# Local SQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/paws2
spring.datasource.username=root1
spring.datasource.password=@root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# --- HTTPS / TLS Configuration ---
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Cubano1967
server.ssl.key-store-type=PKCS12